server:
  port: 8080

spring:
  application:
    name: college_management_system

  datasource:
    url: jdbc:mysql://localhost:3306/college_management_system?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MySQLDialect

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

# ----------------------------------------
# COMMON FILE STORAGE CONFIG
# ----------------------------------------
file-storage:
  base-dir: uploads
  base-url: http://localhost:9090/files   # UPDATED PORT

# --------------------------
# STUDENT QR CONFIGURATION
# --------------------------
buspass:
  qr:
    secret-key: 12345678901234567890123456789012
    width: 250
    height: 250
    base-dir: ${file-storage.base-dir}/qr/students
    base-url: ${file-storage.base-url}/qr/students   # UPDATED PORT
    file-extension: .png

# --------------------------
# STUDENT PHOTO CONFIGURATION
# --------------------------
photo:
  base-dir: ${file-storage.base-dir}/photos/students
  base-url: ${file-storage.base-url}/photos/students   # UPDATED PORT
  file-extension: .jpg

logging:
  level:
    root: INFO
    org.springframework: INFO
    com.cms: DEBUG
